In [7]:
# --- PATIENT ---
import pandas as pd 
df = pd.read_json("database/crafting_profit.json")
df = df.convert_dtypes()
# df.dtypes

In [3]:
# --- INSTANT ---
import pandas as pd 
df = pd.read_json("database/instant_crafting_profit.json")
df = df.convert_dtypes()
# df.dtypes

In [ ]:
# --- PATIENT ---
df = df[df['disciplines_str'].str.contains("Chef|Armorsmith")]

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
	display(df[[	
		'item_name',
		'sell_price',
		'crafting_price',
		'crafting_profit',
		'crf_prf_estimate',
		'crafting_roi',
		'7d_sell_sold',
		'1d_sell_sold',
		'7d_SL_diff',
		'1d_SL_diff',
		'1d_5%_SS',
		'difficult',
		'disciplines'
		]]

	.loc	[
		(df['difficult'] == False) &
		(df['crafting_profit'] > df['flip_profit']) &
		(df['crafting_profit'] > 1) &
		(df['1d_SL_diff'] > -10) &
		(df['7d_SL_diff'] > -10) &
		(df['1d_sell_sold'] > 100) &
		(df['7d_sell_sold'] > 700) 
		]

	# .sort_values(by='crafting_profit', ascending=False)
	.sort_values(by='crf_prf_estimate', ascending=False)

	# .head(30)
	.style.hide_index()
	# .shape[0]
	)

In [5]:
# --- INSTANT ---
df = df[df['disciplines_str'].str.contains("Chef|Armorsmith")]

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
	display(df[[	
		'item_name',
		'sell_price',
		'crafting_price',
		'crafting_profit_INS',
		'crafting_roi_INS',
		'7d_buy_listed',
		'7d_buy_sold',
		'difficult',
		'disciplines'
		]]

	.loc	[
		(df['difficult'] == False) &
		(df['crafting_profit_INS'] > 1) &
		# (df['7d_buy_listed'] > 900) #&
		(df['7d_buy_listed'] > 1) #&
		# (df['7d_buy_sold'] > 200) 
		]

	.sort_values(by='crafting_profit_INS', ascending=False)
	# .sort_values(by='7d_buy_listed', ascending=False)

	# .head(30)
	.style.hide_index()
	# .shape[0]
	)

## What am I currently crafting ##

## What am I currently crafting for instant sell ##
- Celestial Draconic Pauldrons

## What I was crafting for sell ##
- Cup of Light-Roasted Coffee
- 5x Mystic Aspect
- 300x Raspberry Peach Compote	
- 300x Bowl of "Elon Red"

## What I was crafting for instant sell ##
- Cleric's Gladiator Gauntlets
- Commander's Draconic Boots
- Celestial Draconic Pauldrons

## Everyday time gated crafts ##
- Plate of Piquant Plant Food
- Lump of Mithrillium
- charged quartz crystal